### ISSUE TITLE
Lens.org token free trial query

### ISSUE THREAD

**Issue by mcguinlu** [nealhaddaway/citationchaser#4]
Hi @nealhaddaway 

This looks like a great package! One thing to flag from an "openness" point of view is that when I signed-up, Lens.org came back to say that I could have a free trial but would need to pay for institutional access after that. Might be worth flagging this (that you need to pay for persistent access) in the packages README?

> Thanks for this request.  You will be granted a 14-day free trial to enable you to download the data needed.  You will receive shortly an email with instructions on how to generate your token.  Please make sure to download your data within the allocated time.  For any continued access, your library or your institution would need to take up a paid subscription to help support the public resource of the Lens and take advantage new added-value institutional tools.  Please remember to read carefully the Lens data terms of use.

**Comment by nealhaddaway** [comment]
Yeah - this is the sad bit. I had this discussion with Gilad Feldman on Twitter, too. It's open code in taht it is reproducible analytically, but the call isn't. Arguably, the content of the database isn't reproducible anyway because it's continually expanding. I'd also add that other databases are similarly held behind paywalls. But I'm working on a long-term solution so that people don't need one. The Lens is a notforprofit project so long-term I think this kind of organisation is far better to support than databases run by publishers with massive profits. It's also worth asking if they can give you a longer-term solution for research purposes.
________________________________

**Comment by mcguinlu** [comment]
@nealhaddaway - I agree with all of your points completely (particularly the "let's not give for-profit companies more money" one!). I think my message got a little lost though - I'm not saying this approach is the wrong one, just that it could be worth documenting it accurately/completely so that users know what to expect upfront.

For example, I assumed (based on my experience with other R packages where you need an API token) that it would be i) an automated process, where by signing up, I was automatically assigned a token rather than having to wait for approval, and ii) that I would have persistent access but that the access may be rate limited. The response from Lens went against both of these assumptions, and so surprised me!

**Comment by nealhaddaway** [comment]
Ah OK - fair dos - I'm not familiar with API token requests, so that's good to know! Thanks :) I'll add a comment on that.
________________________________

**Comment by nealhaddaway** [comment]
I've now added that note to the README.
